### ISSUE TITLE
serialport-renderer-process 项目什么都没改，dev正常，build打包报错

### ISSUE THREAD

**Issue by do-your-think** [caoxiemeihao/electron-vite-samples#12]
serialport-renderer-process 项目什么都没改，dev正常，build打包报错：

node:internal/modules/cjs/loader:1084 Uncaught Error: Cannot find module '@serialport/parser-byte-length'
Require stack:
- D:\HK\Obj\Electron\serialport-renderer-process\release\0.0.0\win-unpacked\resources\app\node_modules\serialport\dist\index.js
- D:\HK\Obj\Electron\serialport-renderer-process\release\0.0.0\win-unpacked\resources\app\dist\index.html
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/renderer_init:2:3225)
    at node:internal/modules/cjs/loader:929:27
    at Function.<anonymous> (node:electron/js2c/asar_bundle:2:13327)
    at Function._load (node:electron/js2c/renderer_init:2:2455)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\HK\Obj\Electron\s…dist\index.js:17:14)
    at Object.<anonymous> (D:\HK\Obj\Electron\s…\dist\index.js:30:3)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)

**Comment by do-your-think** [comment]
是因为我使用了pnpm build导致，使用npm build重新打包，可以了，请关闭
